# Generated by Django 3.1 on 2021-01-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
