# Generated by Django 3.1 on 2021-01-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210109_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(db_index=True, default='some_author', max_length=150),
        ),
    ]
